version: '2'
services:
    api:
        build: ./API
        ports:
            - "5000:5000"
        container_name: api
        depends_on:
            - redis
    redis:
        image: redis
        container_name: redis
    bot:
        build: ./BOT
        container_name: bot